openapi: 3.0.0
info:
  license:
    name: MIT
  title: OurGroceries REST API
  version: v1
servers:
  - url: 'http://ourgroceries-rest-api/v1'
paths:
  /version:
    get:
      operationId: getVersion
      responses:
        '200':
          description: Get the version of the service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
  /lists:
    get:
      operationId: getLists
      responses:
        '200':
          description: Get the lists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/List'
components:
  schemas:
    List:
      properties:
        name:
          type: string
          example: "n8w1aAoqqURBrM2nUns6nQ"
        id:
          type: string
          example: "The Shopping List"
    Version:
      properties:
        api:
          type: integer
          example: 1
        commit:
          type: string
          example: '423322c'
        date:
          type: string
          example: '2019-06-17T21:05Z'
